// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteServiceCatalogParams creates a new DeleteServiceCatalogParams object
// with the default values initialized.
func NewDeleteServiceCatalogParams() *DeleteServiceCatalogParams {
	var ()
	return &DeleteServiceCatalogParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteServiceCatalogParamsWithTimeout creates a new DeleteServiceCatalogParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteServiceCatalogParamsWithTimeout(timeout time.Duration) *DeleteServiceCatalogParams {
	var ()
	return &DeleteServiceCatalogParams{

		timeout: timeout,
	}
}

// NewDeleteServiceCatalogParamsWithContext creates a new DeleteServiceCatalogParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteServiceCatalogParamsWithContext(ctx context.Context) *DeleteServiceCatalogParams {
	var ()
	return &DeleteServiceCatalogParams{

		Context: ctx,
	}
}

// NewDeleteServiceCatalogParamsWithHTTPClient creates a new DeleteServiceCatalogParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteServiceCatalogParamsWithHTTPClient(client *http.Client) *DeleteServiceCatalogParams {
	var ()
	return &DeleteServiceCatalogParams{
		HTTPClient: client,
	}
}

/*DeleteServiceCatalogParams contains all the parameters to send to the API endpoint
for the delete service catalog operation typically these are written to a http.Request
*/
type DeleteServiceCatalogParams struct {

	/*Cascade
	  If true then all objects owned by this object will be deleted too.

	*/
	Cascade *bool
	/*Name
	  The name of the service catalog you wish to delete

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete service catalog params
func (o *DeleteServiceCatalogParams) WithTimeout(timeout time.Duration) *DeleteServiceCatalogParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete service catalog params
func (o *DeleteServiceCatalogParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete service catalog params
func (o *DeleteServiceCatalogParams) WithContext(ctx context.Context) *DeleteServiceCatalogParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete service catalog params
func (o *DeleteServiceCatalogParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete service catalog params
func (o *DeleteServiceCatalogParams) WithHTTPClient(client *http.Client) *DeleteServiceCatalogParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete service catalog params
func (o *DeleteServiceCatalogParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCascade adds the cascade to the delete service catalog params
func (o *DeleteServiceCatalogParams) WithCascade(cascade *bool) *DeleteServiceCatalogParams {
	o.SetCascade(cascade)
	return o
}

// SetCascade adds the cascade to the delete service catalog params
func (o *DeleteServiceCatalogParams) SetCascade(cascade *bool) {
	o.Cascade = cascade
}

// WithName adds the name to the delete service catalog params
func (o *DeleteServiceCatalogParams) WithName(name string) *DeleteServiceCatalogParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the delete service catalog params
func (o *DeleteServiceCatalogParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteServiceCatalogParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Cascade != nil {

		// query param cascade
		var qrCascade bool
		if o.Cascade != nil {
			qrCascade = *o.Cascade
		}
		qCascade := swag.FormatBool(qrCascade)
		if qCascade != "" {
			if err := r.SetQueryParam("cascade", qCascade); err != nil {
				return err
			}
		}

	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
