// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteUserBasicauthParams creates a new DeleteUserBasicauthParams object
// with the default values initialized.
func NewDeleteUserBasicauthParams() *DeleteUserBasicauthParams {
	var ()
	return &DeleteUserBasicauthParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteUserBasicauthParamsWithTimeout creates a new DeleteUserBasicauthParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteUserBasicauthParamsWithTimeout(timeout time.Duration) *DeleteUserBasicauthParams {
	var ()
	return &DeleteUserBasicauthParams{

		timeout: timeout,
	}
}

// NewDeleteUserBasicauthParamsWithContext creates a new DeleteUserBasicauthParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteUserBasicauthParamsWithContext(ctx context.Context) *DeleteUserBasicauthParams {
	var ()
	return &DeleteUserBasicauthParams{

		Context: ctx,
	}
}

// NewDeleteUserBasicauthParamsWithHTTPClient creates a new DeleteUserBasicauthParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteUserBasicauthParamsWithHTTPClient(client *http.Client) *DeleteUserBasicauthParams {
	var ()
	return &DeleteUserBasicauthParams{
		HTTPClient: client,
	}
}

/*DeleteUserBasicauthParams contains all the parameters to send to the API endpoint
for the delete user basicauth operation typically these are written to a http.Request
*/
type DeleteUserBasicauthParams struct {

	/*User
	  The name of the user we are deletingg

	*/
	User string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete user basicauth params
func (o *DeleteUserBasicauthParams) WithTimeout(timeout time.Duration) *DeleteUserBasicauthParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete user basicauth params
func (o *DeleteUserBasicauthParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete user basicauth params
func (o *DeleteUserBasicauthParams) WithContext(ctx context.Context) *DeleteUserBasicauthParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete user basicauth params
func (o *DeleteUserBasicauthParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete user basicauth params
func (o *DeleteUserBasicauthParams) WithHTTPClient(client *http.Client) *DeleteUserBasicauthParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete user basicauth params
func (o *DeleteUserBasicauthParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUser adds the user to the delete user basicauth params
func (o *DeleteUserBasicauthParams) WithUser(user string) *DeleteUserBasicauthParams {
	o.SetUser(user)
	return o
}

// SetUser adds the user to the delete user basicauth params
func (o *DeleteUserBasicauthParams) SetUser(user string) {
	o.User = user
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteUserBasicauthParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param user
	if err := r.SetPathParam("user", o.User); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
