// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/appvia/kore/pkg/apiclient/models"
)

// DeleteUserBasicauthReader is a Reader for the DeleteUserBasicauth structure.
type DeleteUserBasicauthReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteUserBasicauthReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteUserBasicauthOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteUserBasicauthUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteUserBasicauthForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteUserBasicauthNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteUserBasicauthInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteUserBasicauthOK creates a DeleteUserBasicauthOK with default headers values
func NewDeleteUserBasicauthOK() *DeleteUserBasicauthOK {
	return &DeleteUserBasicauthOK{}
}

/*DeleteUserBasicauthOK handles this case with default header values.

Contains the identities definitions from the kore
*/
type DeleteUserBasicauthOK struct {
}

func (o *DeleteUserBasicauthOK) Error() string {
	return fmt.Sprintf("[DELETE /api/v1alpha1/identities/{user}/basicauth][%d] deleteUserBasicauthOK ", 200)
}

func (o *DeleteUserBasicauthOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteUserBasicauthUnauthorized creates a DeleteUserBasicauthUnauthorized with default headers values
func NewDeleteUserBasicauthUnauthorized() *DeleteUserBasicauthUnauthorized {
	return &DeleteUserBasicauthUnauthorized{}
}

/*DeleteUserBasicauthUnauthorized handles this case with default header values.

If not authenticated
*/
type DeleteUserBasicauthUnauthorized struct {
}

func (o *DeleteUserBasicauthUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /api/v1alpha1/identities/{user}/basicauth][%d] deleteUserBasicauthUnauthorized ", 401)
}

func (o *DeleteUserBasicauthUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteUserBasicauthForbidden creates a DeleteUserBasicauthForbidden with default headers values
func NewDeleteUserBasicauthForbidden() *DeleteUserBasicauthForbidden {
	return &DeleteUserBasicauthForbidden{}
}

/*DeleteUserBasicauthForbidden handles this case with default header values.

If authenticated but not authorized
*/
type DeleteUserBasicauthForbidden struct {
}

func (o *DeleteUserBasicauthForbidden) Error() string {
	return fmt.Sprintf("[DELETE /api/v1alpha1/identities/{user}/basicauth][%d] deleteUserBasicauthForbidden ", 403)
}

func (o *DeleteUserBasicauthForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteUserBasicauthNotFound creates a DeleteUserBasicauthNotFound with default headers values
func NewDeleteUserBasicauthNotFound() *DeleteUserBasicauthNotFound {
	return &DeleteUserBasicauthNotFound{}
}

/*DeleteUserBasicauthNotFound handles this case with default header values.

User does not exist
*/
type DeleteUserBasicauthNotFound struct {
}

func (o *DeleteUserBasicauthNotFound) Error() string {
	return fmt.Sprintf("[DELETE /api/v1alpha1/identities/{user}/basicauth][%d] deleteUserBasicauthNotFound ", 404)
}

func (o *DeleteUserBasicauthNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteUserBasicauthInternalServerError creates a DeleteUserBasicauthInternalServerError with default headers values
func NewDeleteUserBasicauthInternalServerError() *DeleteUserBasicauthInternalServerError {
	return &DeleteUserBasicauthInternalServerError{}
}

/*DeleteUserBasicauthInternalServerError handles this case with default header values.

A generic API error containing the cause of the error
*/
type DeleteUserBasicauthInternalServerError struct {
	Payload *models.ApiserverError
}

func (o *DeleteUserBasicauthInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /api/v1alpha1/identities/{user}/basicauth][%d] deleteUserBasicauthInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteUserBasicauthInternalServerError) GetPayload() *models.ApiserverError {
	return o.Payload
}

func (o *DeleteUserBasicauthInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApiserverError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
