// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetServiceCatalogParams creates a new GetServiceCatalogParams object
// with the default values initialized.
func NewGetServiceCatalogParams() *GetServiceCatalogParams {
	var ()
	return &GetServiceCatalogParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetServiceCatalogParamsWithTimeout creates a new GetServiceCatalogParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetServiceCatalogParamsWithTimeout(timeout time.Duration) *GetServiceCatalogParams {
	var ()
	return &GetServiceCatalogParams{

		timeout: timeout,
	}
}

// NewGetServiceCatalogParamsWithContext creates a new GetServiceCatalogParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetServiceCatalogParamsWithContext(ctx context.Context) *GetServiceCatalogParams {
	var ()
	return &GetServiceCatalogParams{

		Context: ctx,
	}
}

// NewGetServiceCatalogParamsWithHTTPClient creates a new GetServiceCatalogParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetServiceCatalogParamsWithHTTPClient(client *http.Client) *GetServiceCatalogParams {
	var ()
	return &GetServiceCatalogParams{
		HTTPClient: client,
	}
}

/*GetServiceCatalogParams contains all the parameters to send to the API endpoint
for the get service catalog operation typically these are written to a http.Request
*/
type GetServiceCatalogParams struct {

	/*Name
	  The name of the service catalog you wish to retrieve

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get service catalog params
func (o *GetServiceCatalogParams) WithTimeout(timeout time.Duration) *GetServiceCatalogParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get service catalog params
func (o *GetServiceCatalogParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get service catalog params
func (o *GetServiceCatalogParams) WithContext(ctx context.Context) *GetServiceCatalogParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get service catalog params
func (o *GetServiceCatalogParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get service catalog params
func (o *GetServiceCatalogParams) WithHTTPClient(client *http.Client) *GetServiceCatalogParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get service catalog params
func (o *GetServiceCatalogParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get service catalog params
func (o *GetServiceCatalogParams) WithName(name string) *GetServiceCatalogParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get service catalog params
func (o *GetServiceCatalogParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetServiceCatalogParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
