// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/appvia/kore/pkg/apiclient/models"
)

// NewGetTokenParams creates a new GetTokenParams object
// with the default values initialized.
func NewGetTokenParams() *GetTokenParams {
	var ()
	return &GetTokenParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTokenParamsWithTimeout creates a new GetTokenParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTokenParamsWithTimeout(timeout time.Duration) *GetTokenParams {
	var ()
	return &GetTokenParams{

		timeout: timeout,
	}
}

// NewGetTokenParamsWithContext creates a new GetTokenParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTokenParamsWithContext(ctx context.Context) *GetTokenParams {
	var ()
	return &GetTokenParams{

		Context: ctx,
	}
}

// NewGetTokenParamsWithHTTPClient creates a new GetTokenParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTokenParamsWithHTTPClient(client *http.Client) *GetTokenParams {
	var ()
	return &GetTokenParams{
		HTTPClient: client,
	}
}

/*GetTokenParams contains all the parameters to send to the API endpoint
for the get token operation typically these are written to a http.Request
*/
type GetTokenParams struct {

	/*Body*/
	Body *models.TypesIssuedToken

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get token params
func (o *GetTokenParams) WithTimeout(timeout time.Duration) *GetTokenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get token params
func (o *GetTokenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get token params
func (o *GetTokenParams) WithContext(ctx context.Context) *GetTokenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get token params
func (o *GetTokenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get token params
func (o *GetTokenParams) WithHTTPClient(client *http.Client) *GetTokenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get token params
func (o *GetTokenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the get token params
func (o *GetTokenParams) WithBody(body *models.TypesIssuedToken) *GetTokenParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the get token params
func (o *GetTokenParams) SetBody(body *models.TypesIssuedToken) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *GetTokenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
