// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/appvia/kore/pkg/apiclient/models"
)

// GetTokenReader is a Reader for the GetToken structure.
type GetTokenReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTokenReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTokenOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetTokenUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetTokenForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetTokenInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetTokenOK creates a GetTokenOK with default headers values
func NewGetTokenOK() *GetTokenOK {
	return &GetTokenOK{}
}

/*GetTokenOK handles this case with default header values.

An access token which can be used for accessing Kore
*/
type GetTokenOK struct {
	Payload *models.TypesIssuedToken
}

func (o *GetTokenOK) Error() string {
	return fmt.Sprintf("[POST /api/v1alpha1/login/token][%d] getTokenOK  %+v", 200, o.Payload)
}

func (o *GetTokenOK) GetPayload() *models.TypesIssuedToken {
	return o.Payload
}

func (o *GetTokenOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TypesIssuedToken)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTokenUnauthorized creates a GetTokenUnauthorized with default headers values
func NewGetTokenUnauthorized() *GetTokenUnauthorized {
	return &GetTokenUnauthorized{}
}

/*GetTokenUnauthorized handles this case with default header values.

If not authenticated
*/
type GetTokenUnauthorized struct {
}

func (o *GetTokenUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/v1alpha1/login/token][%d] getTokenUnauthorized ", 401)
}

func (o *GetTokenUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetTokenForbidden creates a GetTokenForbidden with default headers values
func NewGetTokenForbidden() *GetTokenForbidden {
	return &GetTokenForbidden{}
}

/*GetTokenForbidden handles this case with default header values.

If authenticated but not authorized
*/
type GetTokenForbidden struct {
}

func (o *GetTokenForbidden) Error() string {
	return fmt.Sprintf("[POST /api/v1alpha1/login/token][%d] getTokenForbidden ", 403)
}

func (o *GetTokenForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetTokenInternalServerError creates a GetTokenInternalServerError with default headers values
func NewGetTokenInternalServerError() *GetTokenInternalServerError {
	return &GetTokenInternalServerError{}
}

/*GetTokenInternalServerError handles this case with default header values.

A generic API error containing the cause of the error
*/
type GetTokenInternalServerError struct {
	Payload *models.ApiserverError
}

func (o *GetTokenInternalServerError) Error() string {
	return fmt.Sprintf("[POST /api/v1alpha1/login/token][%d] getTokenInternalServerError  %+v", 500, o.Payload)
}

func (o *GetTokenInternalServerError) GetPayload() *models.ApiserverError {
	return o.Payload
}

func (o *GetTokenInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApiserverError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
