// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/appvia/kore/pkg/apiclient/models"
)

// ListServiceCatalogsReader is a Reader for the ListServiceCatalogs structure.
type ListServiceCatalogsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListServiceCatalogsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListServiceCatalogsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewListServiceCatalogsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewListServiceCatalogsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListServiceCatalogsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListServiceCatalogsOK creates a ListServiceCatalogsOK with default headers values
func NewListServiceCatalogsOK() *ListServiceCatalogsOK {
	return &ListServiceCatalogsOK{}
}

/*ListServiceCatalogsOK handles this case with default header values.

A list of service catalogs
*/
type ListServiceCatalogsOK struct {
	Payload *models.V1ServiceCatalogList
}

func (o *ListServiceCatalogsOK) Error() string {
	return fmt.Sprintf("[GET /api/v1alpha1/servicecatalogs][%d] listServiceCatalogsOK  %+v", 200, o.Payload)
}

func (o *ListServiceCatalogsOK) GetPayload() *models.V1ServiceCatalogList {
	return o.Payload
}

func (o *ListServiceCatalogsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1ServiceCatalogList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListServiceCatalogsUnauthorized creates a ListServiceCatalogsUnauthorized with default headers values
func NewListServiceCatalogsUnauthorized() *ListServiceCatalogsUnauthorized {
	return &ListServiceCatalogsUnauthorized{}
}

/*ListServiceCatalogsUnauthorized handles this case with default header values.

If not authenticated
*/
type ListServiceCatalogsUnauthorized struct {
}

func (o *ListServiceCatalogsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v1alpha1/servicecatalogs][%d] listServiceCatalogsUnauthorized ", 401)
}

func (o *ListServiceCatalogsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListServiceCatalogsForbidden creates a ListServiceCatalogsForbidden with default headers values
func NewListServiceCatalogsForbidden() *ListServiceCatalogsForbidden {
	return &ListServiceCatalogsForbidden{}
}

/*ListServiceCatalogsForbidden handles this case with default header values.

If authenticated but not authorized
*/
type ListServiceCatalogsForbidden struct {
}

func (o *ListServiceCatalogsForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v1alpha1/servicecatalogs][%d] listServiceCatalogsForbidden ", 403)
}

func (o *ListServiceCatalogsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListServiceCatalogsInternalServerError creates a ListServiceCatalogsInternalServerError with default headers values
func NewListServiceCatalogsInternalServerError() *ListServiceCatalogsInternalServerError {
	return &ListServiceCatalogsInternalServerError{}
}

/*ListServiceCatalogsInternalServerError handles this case with default header values.

A generic API error containing the cause of the error
*/
type ListServiceCatalogsInternalServerError struct {
	Payload *models.ApiserverError
}

func (o *ListServiceCatalogsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v1alpha1/servicecatalogs][%d] listServiceCatalogsInternalServerError  %+v", 500, o.Payload)
}

func (o *ListServiceCatalogsInternalServerError) GetPayload() *models.ApiserverError {
	return o.Payload
}

func (o *ListServiceCatalogsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApiserverError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
