// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListServiceCatalogsParams creates a new ListServiceCatalogsParams object
// with the default values initialized.
func NewListServiceCatalogsParams() *ListServiceCatalogsParams {

	return &ListServiceCatalogsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListServiceCatalogsParamsWithTimeout creates a new ListServiceCatalogsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListServiceCatalogsParamsWithTimeout(timeout time.Duration) *ListServiceCatalogsParams {

	return &ListServiceCatalogsParams{

		timeout: timeout,
	}
}

// NewListServiceCatalogsParamsWithContext creates a new ListServiceCatalogsParams object
// with the default values initialized, and the ability to set a context for a request
func NewListServiceCatalogsParamsWithContext(ctx context.Context) *ListServiceCatalogsParams {

	return &ListServiceCatalogsParams{

		Context: ctx,
	}
}

// NewListServiceCatalogsParamsWithHTTPClient creates a new ListServiceCatalogsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListServiceCatalogsParamsWithHTTPClient(client *http.Client) *ListServiceCatalogsParams {

	return &ListServiceCatalogsParams{
		HTTPClient: client,
	}
}

/*ListServiceCatalogsParams contains all the parameters to send to the API endpoint
for the list service catalogs operation typically these are written to a http.Request
*/
type ListServiceCatalogsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list service catalogs params
func (o *ListServiceCatalogsParams) WithTimeout(timeout time.Duration) *ListServiceCatalogsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list service catalogs params
func (o *ListServiceCatalogsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list service catalogs params
func (o *ListServiceCatalogsParams) WithContext(ctx context.Context) *ListServiceCatalogsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list service catalogs params
func (o *ListServiceCatalogsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list service catalogs params
func (o *ListServiceCatalogsParams) WithHTTPClient(client *http.Client) *ListServiceCatalogsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list service catalogs params
func (o *ListServiceCatalogsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListServiceCatalogsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
