// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/appvia/kore/pkg/apiclient/models"
)

// NewUpdateServiceCatalogParams creates a new UpdateServiceCatalogParams object
// with the default values initialized.
func NewUpdateServiceCatalogParams() *UpdateServiceCatalogParams {
	var ()
	return &UpdateServiceCatalogParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateServiceCatalogParamsWithTimeout creates a new UpdateServiceCatalogParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateServiceCatalogParamsWithTimeout(timeout time.Duration) *UpdateServiceCatalogParams {
	var ()
	return &UpdateServiceCatalogParams{

		timeout: timeout,
	}
}

// NewUpdateServiceCatalogParamsWithContext creates a new UpdateServiceCatalogParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateServiceCatalogParamsWithContext(ctx context.Context) *UpdateServiceCatalogParams {
	var ()
	return &UpdateServiceCatalogParams{

		Context: ctx,
	}
}

// NewUpdateServiceCatalogParamsWithHTTPClient creates a new UpdateServiceCatalogParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateServiceCatalogParamsWithHTTPClient(client *http.Client) *UpdateServiceCatalogParams {
	var ()
	return &UpdateServiceCatalogParams{
		HTTPClient: client,
	}
}

/*UpdateServiceCatalogParams contains all the parameters to send to the API endpoint
for the update service catalog operation typically these are written to a http.Request
*/
type UpdateServiceCatalogParams struct {

	/*Body
	  The specification for the service catalog you are creating or updating

	*/
	Body *models.V1ServiceCatalog
	/*Name
	  The name of the service catalog you wish to create or update

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update service catalog params
func (o *UpdateServiceCatalogParams) WithTimeout(timeout time.Duration) *UpdateServiceCatalogParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update service catalog params
func (o *UpdateServiceCatalogParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update service catalog params
func (o *UpdateServiceCatalogParams) WithContext(ctx context.Context) *UpdateServiceCatalogParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update service catalog params
func (o *UpdateServiceCatalogParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update service catalog params
func (o *UpdateServiceCatalogParams) WithHTTPClient(client *http.Client) *UpdateServiceCatalogParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update service catalog params
func (o *UpdateServiceCatalogParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update service catalog params
func (o *UpdateServiceCatalogParams) WithBody(body *models.V1ServiceCatalog) *UpdateServiceCatalogParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update service catalog params
func (o *UpdateServiceCatalogParams) SetBody(body *models.V1ServiceCatalog) {
	o.Body = body
}

// WithName adds the name to the update service catalog params
func (o *UpdateServiceCatalogParams) WithName(name string) *UpdateServiceCatalogParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the update service catalog params
func (o *UpdateServiceCatalogParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateServiceCatalogParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
