apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: kube-system
spec:
  componentKinds:
    - group: apps
      kind: Deployment
  selector:
    matchLabels:
      app: cluster-autoscaler
