// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TypesIssuedToken types issued token
//
// swagger:model types.IssuedToken
type TypesIssuedToken struct {

	// expires
	Expires int64 `json:"expires,omitempty"`

	// refresh token
	RefreshToken string `json:"refreshToken,omitempty"`

	// token
	Token string `json:"token,omitempty"`
}

// Validate validates this types issued token
func (m *TypesIssuedToken) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TypesIssuedToken) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TypesIssuedToken) UnmarshalBinary(b []byte) error {
	var res TypesIssuedToken
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
