// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V1ServiceCatalogSpec v1 service catalog spec
//
// swagger:model v1.ServiceCatalogSpec
type V1ServiceCatalogSpec struct {

	// description
	Description string `json:"description,omitempty"`

	// display name
	DisplayName string `json:"displayName,omitempty"`

	// service kind prefix
	// Required: true
	ServiceKindPrefix *string `json:"serviceKindPrefix"`

	// summary
	// Required: true
	Summary *string `json:"summary"`

	// url
	// Required: true
	URL *string `json:"url"`
}

// Validate validates this v1 service catalog spec
func (m *V1ServiceCatalogSpec) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateServiceKindPrefix(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSummary(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateURL(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1ServiceCatalogSpec) validateServiceKindPrefix(formats strfmt.Registry) error {

	if err := validate.Required("serviceKindPrefix", "body", m.ServiceKindPrefix); err != nil {
		return err
	}

	return nil
}

func (m *V1ServiceCatalogSpec) validateSummary(formats strfmt.Registry) error {

	if err := validate.Required("summary", "body", m.Summary); err != nil {
		return err
	}

	return nil
}

func (m *V1ServiceCatalogSpec) validateURL(formats strfmt.Registry) error {

	if err := validate.Required("url", "body", m.URL); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1ServiceCatalogSpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1ServiceCatalogSpec) UnmarshalBinary(b []byte) error {
	var res V1ServiceCatalogSpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
