// Code generated by struct-gen; DO NOT EDIT.

package application

// Kubernetes Application defined by raw resources
type AppV1 struct {
	// Resources Kubernetes resource definitions in YAML format. It supports Go text/template expressions. Values can be referenced as '{{ .Values.<parameter name> }}'.
	Resources string `json:"resources"`
	// Values A set of key-values to use as template parameters in the Kubernetes resoure defintions.
	Values map[string]interface{} `json:"values,omitempty"`
}
