// Code generated by struct-gen; DO NOT EDIT.

package application

// Kubernetes Application defined by a Helm package
type HelmAppV1 struct {
	ResourceKinds    []HelmAppV1ResourceKind    `json:"resourceKinds,omitempty"`
	ResourceSelector *HelmAppV1ResourceSelector `json:"resourceSelector,omitempty"`
	Source           HelmAppV1Source            `json:"source"`
	// Values A set of key-values to use as template parameters in the Kubernetes resoure defintions.
	Values map[string]interface{} `json:"values,omitempty"`
}

type HelmAppV1Git struct {
	// Path The path to the chart relative to the repository root
	Path string `json:"path,omitempty"`
	// Ref The Git branch (or other reference) to use
	Ref string `json:"ref"`
	// URL The URL of the Git repository
	URL string `json:"url"`
}

type HelmAppV1Helm struct {
	// Name The name of the Helm chart (without an alias)
	Name string `json:"name"`
	// URL The URL of the Helm repository
	URL string `json:"url"`
	// Version The targeted Helm chart version
	Version string `json:"version"`
}

type HelmAppV1MatchLabel string

type HelmAppV1ResourceKind struct {
	// Group Kubernetes API group
	Group string `json:"group,omitempty"`
	// Kind Kubernetes resource kind
	Kind string `json:"kind"`
}

type HelmAppV1ResourceSelector struct {
	MatchLabels map[string]HelmAppV1MatchLabel `json:"matchLabels"`
}

type HelmAppV1Source struct {
	Git  *HelmAppV1Git  `json:"git,omitempty"`
	Helm *HelmAppV1Helm `json:"helm,omitempty"`
}
