apiVersion: v1
kind: Secret
metadata:
  name: cloudinfo
  namespace: kore-costs
  labels:
    app.kubernetes.io/name: "kore-costs"
type: Opaque
stringData:
  config.yaml: |-
    app:
      basePath: /
    log:
      level: debug
    metrics:
      enabled: true
    config:
      vault:
    store:
      redis:
        enabled: true
        host: redis.kore-costs.svc.cluster.local
        port: 6379
    provider:
      amazon:
        enabled: {{if .Secrets.aws_access_key}}true{{else}}false{{end}}
        accessKey: {{.Secrets.aws_access_key}}
        secretKey: {{.Secrets.aws_secret_key}}
      google:
        enabled: {{if .Secrets.gcp_credentials}}true{{else}}false{{end}}
        credentials: {{ jsonb64 .Secrets.gcp_credentials}}
      azure:
        enabled: {{if .Secrets.azure_subscription_id}}true{{else}}false{{end}}
        subscriptionId: {{.Secrets.azure_subscription_id}}
        clientId: {{.Secrets.azure_client_id}}
        clientSecret: {{.Secrets.azure_client_secret}}
        tenantId: {{.Secrets.azure_tenant_id}}
