apiVersion: v1
kind: Secret
metadata:
  name: cloudinfo
  namespace: kore-costs
  labels:
    app.kubernetes.io/name: "kore-costs"
type: Opaque
stringData:
  config.yaml: |
    app:
      basePath: /
    log:
      level: info
    metrics:
      enabled: true
    config:
      vault:
    store:
      redis:
        enabled: true
        host: redis.kore-costs.svc.cluster.local
        port: 6379
    provider:
      amazon:
        enabled: false
        accessKey: ""
        secretKey: ""
      google:
        enabled: false
        credentials: ""
      azure:
        enabled: false
        subscriptionId: ""
        clientId: ""
        clientSecret: ""
        tenantId: ""
