---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: kore-costs
  labels:
    name: redis
    app.kubernetes.io/name: "kore-costs"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis
      app.kubernetes.io/name: "kore-costs"
  template:
    metadata:
      labels:
        name: redis
        app.kubernetes.io/name: "kore-costs"
    spec:
      containers:
        - name: redis
          image: redis:5.0
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: kore-costs
  labels:
    name: redis
    app.kubernetes.io/name: "kore-costs"
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  sessionAffinity: ClientIP
  selector:
    name: redis