// Code generated by struct-gen; DO NOT EDIT.

package dummy

// Dummy service plan schema
type ProviderSchemaV2 struct {
	IAmDummy      string `json:"iAmDummy"`
	IAmVersionTwo string `json:"iAmVersionTwo"`
}
