apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
      app.kubernetes.io/name: {{ .Release.Name }}
spec:
  componentKinds:
    - group: apps
      kind: Deployment
    - group: batch/v1beta1
      kind: CronJob
    - group: v1
      kind: Service
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
