apiVersion: v1
kind: Secret
metadata:
  name: cloudinfo
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
type: Opaque
stringData:
  config.yaml: |-
    app:
      basePath: /
    log:
      level: debug
    metrics:
      enabled: true
    config:
      vault:
    store:
      redis:
        enabled: true
        host: redis.{{ .Release.Namespace }}.svc.cluster.local
        port: 6379
    provider:
      {{- if .Values.aws_credentials_secret }}
      {{- with (lookup "config.kore.appvia.io/v1" "Secret" "kore-admin" .Values.aws_credentials_secret) }}
      amazon:
        enabled: true
        accessKey: "{{ .spec.data.access_key_id | b64dec }}"
        secretKey: "{{ .spec.data.access_secret_key | b64dec }}"
      {{- end }}
      {{- end }}
      {{- if .Values.gcp_credentials_secret }}
      {{- with (lookup "config.kore.appvia.io/v1" "Secret" "kore-admin" .Values.gcp_credentials_secret) }}
      google:
        enabled: true
        credentials: "{{ .spec.data.service_account_key }}"
      {{- end }}
      {{- end }}
      {{- if .Values.azure_credentials_secret }}
      {{- with (lookup "config.kore.appvia.io/v1" "Secret" "kore-admin" .Values.azure_credentials_secret) }}
      azure:
        enabled: true
        subscriptionId: "{{ .spec.data.subscription_id | b64dec }}"
        clientId: "{{ .spec.data.client_id | b64dec }}"
        clientSecret: "{{.spec.data.client_secret | b64dec }}"
        tenantId: "{{ .spec.data.tenant_id | b64dec }}"
      {{- end }}
      {{- end }}

