{{- if or .Values.gcp.estimates.enabled .Values.aws.estimates.enabled .Values.azure.estimates.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: cloudinfo
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
type: Opaque
stringData:
  config.yaml: |-
    app:
      basePath: /
    log:
      level: debug
    metrics:
      enabled: true
    config:
      vault:
    store:
      redis:
        enabled: true
        host: redis.{{ .Release.Namespace }}.svc.cluster.local
        port: 6379
    provider:
      {{- if .Values.aws.estimates.credsSecret }}
      {{- with (lookup "config.kore.appvia.io/v1" "Secret" .Values.aws.estimates.credsSecretNamespace .Values.aws.estimates.credsSecret) }}
      amazon:
        enabled: {{ .Values.aws.estimates.enabled }}
        accessKey: "{{ .spec.data.access_key_id | b64dec }}"
        secretKey: "{{ .spec.data.access_secret_key | b64dec }}"
      {{- end }}
      {{- end }}
      {{- if .Values.gcp.estimates.credsSecret }}
      {{- with (lookup "config.kore.appvia.io/v1" "Secret" .Values.gcp.estimates.credsSecretNamespace .Values.gcp.estimates.credsSecret) }}
      google:
        enabled: {{ .Values.gcp.estimates.enabled }}
        credentials: "{{ .spec.data.service_account_key }}"
      {{- end }}
      {{- end }}
      {{- if .Values.azure.estimates.credsSecret }}
      {{- with (lookup "config.kore.appvia.io/v1" "Secret" .Values.azure.estimates.credsSecretNamespace .Values.azure.estimates.credsSecret) }}
      azure:
        enabled: {{ .Values.azure.estimates.enabled }}
        subscriptionId: "{{ .spec.data.subscription_id | b64dec }}"
        clientId: "{{ .spec.data.client_id | b64dec }}"
        clientSecret: "{{.spec.data.client_secret | b64dec }}"
        tenantId: "{{ .spec.data.tenant_id | b64dec }}"
      {{- end }}
      {{- end }}
{{- end}}