{{- if or .Values.gcp.actuals.enabled .Values.aws.actuals.enabled .Values.azure.actuals.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: costsengine-creds
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
type: Opaque
data:
  {{- if and .Values.gcp.actuals.enabled .Values.gcp.actuals.credsSecret }}
  {{- with (lookup "config.kore.appvia.io/v1" "Secret" .Values.gcp.actuals.credsSecretNamespace .Values.gcp.actuals.credsSecret) }}
  gcp-key.json: {{ .spec.data.service_account_key }}
  {{- end}}
  {{- end}}
---
apiVersion: v1
kind: Secret
metadata:
  name: costsengine-kore
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
type: Opaque
stringData:
  KORE_LICENCE: {{ .Values.licence_key }}
  KORE_API_URL: {{ .Values.kore_api_url }}
  {{- if .Values.kore_token }}
  KORE_TOKEN: {{ .Values.kore_token }}
  {{- else}}
  {{- with (lookup "v1" "Secret" "kore" "kore-api") }}
  KORE_TOKEN: {{ .data.KORE_ADMIN_TOKEN | b64dec }}
  {{- end}}
  {{- end}}
{{- end}}