---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudinfo
  namespace: cloudinfo
  labels:
    app.kubernetes.io/name: cloudinfo
    app.kubernetes.io/component: "scraper"
    app.kubernetes.io/managed-by: "kore"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cloudinfo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: cloudinfo
      annotations:
        prometheus.io/scrape: "true"
    spec:
      serviceAccountName: cloudinfo
      volumes:
      containers:
      - name: cloudinfo
        # There are no ":latest" images for helm-operator. Find the most recent
        # release or image version at https://hub.docker.com/r/fluxcd/helm-operator/tags
        # and replace the tag here.
        image: docker.io/banzaicloud/cloudinfo:0.12.0
        imagePullPolicy: IfNotPresent
        args: ["cloudinfo", "--scrape=true", "--config=/etc/cloudinfo/config.yaml", "--listen-address=0.0.0.0:8000"]
        ports:
        - name: http
          containerPort: 8000
        livenessProbe:
          httpGet:
            port: 8000
            path: /status
          initialDelaySeconds: 1
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            port: 8000
            path: /status
          initialDelaySeconds: 1
          timeoutSeconds: 5
        resources:
          # limits:
          #   cpu: 100m
          #   memory: 128Mi
          # requests:
          #   cpu: 100m
          #   memory: 128Mi
        volumeMounts:
          - name: config
            mountPath: /etc/cloudinfo/config.yaml
            subPath: config.yaml
            readOnly: true
      volumes:
        - name: config
          secret:
            secretName: cloudinfo
