apiVersion: v1
kind: Secret
metadata:
  name: cloudinfo
  namespace: cloudinfo
  labels:
    app.kubernetes.io/name: cloudinfo
    app.kubernetes.io/managed-by: kore
type: Opaque
stringData:
  config.yaml: |
    app:
      basePath: /
    log:
      level: info
    metrics:
      enabled: false
    config:
      vault:
        enabled: false
        address: ""
        token: ""
        secretPath: ""
    store:
      redis:
        enabled: false
        host: ""
        port: 6379
    provider:
      amazon:
        enabled: false
        accessKey: ""
        secretKey: ""
      google:
        enabled: false
        credentials: ""
