---
apiVersion: aks.compute.kore.appvia.io/v1alpha1
kind: AKSCredentials
metadata:
  name: example-aks
  namespace: kore-admin
spec:
  subscriptionID: <SUBSCRIPTION ID>
  tenantID: <TENANT ID>
  clientID: <CLIENT ID>
  credentialsRef:
    name: example-aks
    namespace: kore-admin

---
apiVersion: config.kore.appvia.io/v1
kind: Secret
metadata:
  name: example-aks
  namespace: kore-admin
spec:
  data:
    subscription_id: <BASE64-ENCODED SUBSCRIPTION ID>
    tenant_id: <BASE64-ENCODED TENANT ID>
    client_id: <BASE64-ENCODED CLIENT ID>
    client_secret: <BASE64-ENCODED CLIENT SECRET>
  description: Example credentials
  type: azure-credentials

---
apiVersion: config.kore.appvia.io/v1
kind: Allocation
metadata:
  name: akscredentials-example-aks
  namespace: kore-admin
spec:
  name: example-aks
  resource:
    group: aks.compute.kore.appvia.io
    kind: AKSCredentials
    name: example-aks
    namespace: kore-admin
    version: v1alpha1
  summary: Default Credentials for building an AKS Cluster
  teams:
    - '*'
