---
apiVersion: clusters.compute.kore.appvia.io/v1
kind: Cluster
metadata:
  name: test-gke-dev
  namespace: a-team
spec:
  description: Test GKE Plan
  kind: GKE
  plan: gke-development
  credentials:
    group: gke.compute.kore.appvia.io
    version: v1alpha1
    kind: GKECredentials
    name: gke
    namespace: kore-admin
  configuration:
    authProxyAllowedIPs:
      - 0.0.0.0/0
    authorizedMasterNetworks:
      - cidr: 0.0.0.0/0
        name: default
    defaultTeamRole: "cluster-admin"
    description: "This is my test cluster"
    domain: example.appvia.io
    enableHTTPLoadBalancer: true
    enableHorizontalPodAutoscaler: true
    enableIstio: false
    enablePrivateEndpoint: false
    enablePrivateNetwork: false
    enableShieldedNodes: true
    enableStackDriverLogging: true
    enableStackDriverMetrics: true
    enableDefaultTrafficBlock: false
    inheritTeamMembers: true
    maintenanceWindow: "03:00"
    network: default
    region: europe-west2
    version: 1.15
    nodePools: 
      - name: compute
        diskSize: 100
        enableAutorepair: true
        enableAutoscaler: true
        enableAutoupgrade: true
        imageType: COS
        machineType: e2-small
        preemptible: true
        size: 1
        minSize: 1
        maxSize: 10
