---
apiVersion: services.kore.appvia.io/v1
kind: Service
metadata:
  name: kore-monitoring
  namespace: kore-admin
  annotations:
    kore.appvia.io/ignore: "true"
spec:
  kind: helm-app
  summary: Kore Monitoring
  description: Kore Monitoring Operator
  plan: helm-app-kore-monitoring
  cluster:
    group: clusters.compute.kore.appvia.io
    kind: Cluster
    name: kore
    namespace: kore-admin
    version: v1
  clusterNamespace: kore
  configuration:
    source:
      helm:
        url: https://storage.googleapis.com/kore-charts
        name: kore-monitoring
        version: 0.0.1
    resourceKinds:
      - group: apps
        kind: Deployment
      - group: ""
        kind: Service
    values: |+
      prometheus-operator:
        enabled: false
      monitoring-operator:
        fullnameOverride: kore-monitor
        operator:
          enabled: false
        controller:
          enabled: true
          features: [kore]
          config: |+
            # This values are mapped to https://github.com/appvia/charts/blob/master/prometheus-operator/values.yaml#L100
            alertmanager:
              config:
                route:
                  group_wait: 30s
                  group_interval: 5m
                  receiver: monitoring-operator
                  routes:
                    - match:
                        alertname: Watchdog
                      receiver: 'null'
                receivers:
                  - name: 'null'
                  - name: monitoring-operator
                    webhook_configs:
                      - send_resolved: true
                        url: http://kore-monitoring-webhooks.kore-system.svc.cluster.local/apis/v1beta1/webhooks/alert
                        http_config:
                          tls_config:
                            insecure_skip_verify: true
