---
apiVersion: services.kore.appvia.io/v1
kind: ServicePlan
metadata:
  name: helm-app-kore-monitoring
  namespace: kore
spec:
  kind: helm-app
  summary: Kore Monitoring
  displayName: Kore Cluster Monitoring
  description: Managaed Cluster Monitoring
  configuration:
    source:
      helm:
        url: https://storage.googleapis.com/kore-charts/charts
        name: kore-monitoring
        version: 0.0.2
      values: |+
        operator:
          enabled: true
    resourceKinds:
      - group: apps
        kind: Deploymnent
      - group: ""
        kind: Service
---
apiVersion: services.kore.appvia.io/v1
kind: Service
metadata:
  name: kore-monitoring-controller
  namespace: kore-admin
spec:
  kind: helm-app
  summary: Kore Monitoring
  description: Kore Monitoring Operator
  plan: helm-app-kore-monitoring
  cluster:
    group: clusters.compute.kore.appvia.io
    kind: Cluster
    name: kore
    namespace: kore-admin
    version: v1
  clusterNamespace: kore-system
  configuration:
    source:
      helm:
        url: https://storage.googleapis.com/kore-charts/charts
        name: kore-monitoring
        version: 0.0.2
    values: |+
      controller:
        features: [kore]
        enabled: true
      operator:
        enabled: true
    resourceKinds:
      - group: apps
        kind: Deployment
      - group: ""
        kind: Service
