{{- if .Values.ca.generate }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ca.secretName }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
  labels:
{{ include "kore.labels" . | indent 4}}
type: Opaque
data:
  {{- with genCA "kubernetes" 3650 }}
  ca.pem: {{ .Cert | b64enc }}
  ca-key.pem: {{ .Key | b64enc }}
  {{- end }}
{{- end }}

{{- if and .Values.api.tls.enabled (not .Values.api.tls.secretName) }}
{{- if not (lookup "v1" "Secret" .Release.Namespace (printf "%s%s" (include "kore.name" .) "-api-tls")) }}
{{ $ca := genCA "svc-cat-ca" 3650 }}
{{ $dn := printf "kore-apiserver.%s.svc.cluster.local" .Release.Namespace }}
{{ $server := genSignedCert "" (list "127.0.0.1") (list "localhost" "kore-apiserver" $dn) 365 $ca }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kore.name" . }}-api-tls
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
  labels:
{{ include "kore.labels" . | indent 4}}
type: Opaque
data:
  ca.cert: {{ $ca.Cert | b64enc }}
  server.cert: {{ $server.Cert | b64enc }}
  server.key: {{ $server.Key | b64enc }}
{{- end }}
{{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kore.name" . }}-idp
  labels:
{{ include "kore.labels" . | indent 4}}
type: Opaque
stringData:
  {{- if .Values.idp.client_id }}
  KORE_IDP_CLIENT_ID: {{ .Values.idp.client_id }}
  {{- end }}
  KORE_IDP_CLIENT_SCOPES: {{ .Values.idp.client_scopes | join "," }}
  {{- if .Values.idp.client_secret }}
  KORE_IDP_CLIENT_SECRET: {{ .Values.idp.client_secret }}
  {{- end }}
  {{- if .Values.idp.server_url }}
  KORE_IDP_SERVER_URL: {{ .Values.idp.server_url }}
  {{- end }}
  KORE_IDP_USER_CLAIMS: {{ .Values.idp.user_claims | join "," }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kore.name" . }}-mysql
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
  labels:
{{ include "kore.labels" . | indent 4}}
type: Opaque
stringData:
  {{- with randAlphaNum 20 }}
  USERS_DB_URL: root:{{ . }}@tcp({{ include "kore.name" $ }}-mysql:3306)/kore?parseTime=true
  MYSQL_ROOT_PASSWORD: {{ . }}
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: kore-api
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
  labels:
{{ include "kore.labels" . | indent 4}}
type: Opaque
stringData:
  KORE_ADMIN_PASS: {{ or .Values.api.admin_pass (randAlphaNum 32) }}
  KORE_ADMIN_TOKEN: {{ or .Values.api.admin_token (randAlphaNum 32) }}
  KORE_HMAC: {{ or .Values.api.hmac (randAlphaNum 32) }}
