/**
 * Kore API
 * Kore API provides the frontend API (kore.appvia.io)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@appvia.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TypesLocalUser model module.
 * @module model/TypesLocalUser
 * @version 0.0.1
 */
class TypesLocalUser {
    /**
     * Constructs a new <code>TypesLocalUser</code>.
     * @alias module:model/TypesLocalUser
     * @param password {String} 
     * @param username {String} 
     */
    constructor(password, username) { 
        
        TypesLocalUser.initialize(this, password, username);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, password, username) { 
        obj['Password'] = password;
        obj['Username'] = username;
    }

    /**
     * Constructs a <code>TypesLocalUser</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TypesLocalUser} obj Optional instance to populate.
     * @return {module:model/TypesLocalUser} The populated <code>TypesLocalUser</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TypesLocalUser();

            if (data.hasOwnProperty('Password')) {
                obj['Password'] = ApiClient.convertToType(data['Password'], 'String');
            }
            if (data.hasOwnProperty('Username')) {
                obj['Username'] = ApiClient.convertToType(data['Username'], 'String');
            }
        }
        return obj;
    }

/**
     * @return {String}
     */
    getPassword() {
        return this.Password;
    }

    /**
     * @param {String} password
     */
    setPassword(password) {
        this['Password'] = password;
    }
/**
     * @return {String}
     */
    getUsername() {
        return this.Username;
    }

    /**
     * @param {String} username
     */
    setUsername(username) {
        this['Username'] = username;
    }

}

/**
 * @member {String} Password
 */
TypesLocalUser.prototype['Password'] = undefined;

/**
 * @member {String} Username
 */
TypesLocalUser.prototype['Username'] = undefined;






export default TypesLocalUser;

