/**
 * Kore API
 * Kore API provides the frontend API (kore.appvia.io)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@appvia.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TypesIssuedToken model module.
 * @module model/TypesIssuedToken
 * @version 0.0.1
 */
class TypesIssuedToken {
    /**
     * Constructs a new <code>TypesIssuedToken</code>.
     * @alias module:model/TypesIssuedToken
     * @param expires {Number} 
     * @param refreshToken {String} 
     * @param token {String} 
     */
    constructor(expires, refreshToken, token) { 
        
        TypesIssuedToken.initialize(this, expires, refreshToken, token);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, expires, refreshToken, token) { 
        obj['Expires'] = expires;
        obj['RefreshToken'] = refreshToken;
        obj['Token'] = token;
    }

    /**
     * Constructs a <code>TypesIssuedToken</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TypesIssuedToken} obj Optional instance to populate.
     * @return {module:model/TypesIssuedToken} The populated <code>TypesIssuedToken</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TypesIssuedToken();

            if (data.hasOwnProperty('Expires')) {
                obj['Expires'] = ApiClient.convertToType(data['Expires'], 'Number');
            }
            if (data.hasOwnProperty('RefreshToken')) {
                obj['RefreshToken'] = ApiClient.convertToType(data['RefreshToken'], 'String');
            }
            if (data.hasOwnProperty('Token')) {
                obj['Token'] = ApiClient.convertToType(data['Token'], 'String');
            }
        }
        return obj;
    }

/**
     * @return {Number}
     */
    getExpires() {
        return this.Expires;
    }

    /**
     * @param {Number} expires
     */
    setExpires(expires) {
        this['Expires'] = expires;
    }
/**
     * @return {String}
     */
    getRefreshToken() {
        return this.RefreshToken;
    }

    /**
     * @param {String} refreshToken
     */
    setRefreshToken(refreshToken) {
        this['RefreshToken'] = refreshToken;
    }
/**
     * @return {String}
     */
    getToken() {
        return this.Token;
    }

    /**
     * @param {String} token
     */
    setToken(token) {
        this['Token'] = token;
    }

}

/**
 * @member {Number} Expires
 */
TypesIssuedToken.prototype['Expires'] = undefined;

/**
 * @member {String} RefreshToken
 */
TypesIssuedToken.prototype['RefreshToken'] = undefined;

/**
 * @member {String} Token
 */
TypesIssuedToken.prototype['Token'] = undefined;






export default TypesIssuedToken;

