/**
 * Kore API
 * Kore API provides the frontend API (kore.appvia.io)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@appvia.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V1beta1Asset from './V1beta1Asset';

/**
 * The V1beta1AssetList model module.
 * @module model/V1beta1AssetList
 * @version 0.0.1
 */
class V1beta1AssetList {
    /**
     * Constructs a new <code>V1beta1AssetList</code>.
     * @alias module:model/V1beta1AssetList
     * @param items {Array.<module:model/V1beta1Asset>} 
     */
    constructor(items) { 
        
        V1beta1AssetList.initialize(this, items);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, items) { 
        obj['items'] = items;
    }

    /**
     * Constructs a <code>V1beta1AssetList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1beta1AssetList} obj Optional instance to populate.
     * @return {module:model/V1beta1AssetList} The populated <code>V1beta1AssetList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1beta1AssetList();

            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [V1beta1Asset]);
            }
            if (data.hasOwnProperty('koreIdentifier')) {
                obj['koreIdentifier'] = ApiClient.convertToType(data['koreIdentifier'], 'String');
            }
        }
        return obj;
    }

/**
     * @return {Array.<module:model/V1beta1Asset>}
     */
    getItems() {
        return this.items;
    }

    /**
     * @param {Array.<module:model/V1beta1Asset>} items
     */
    setItems(items) {
        this['items'] = items;
    }
/**
     * @return {String}
     */
    getKoreIdentifier() {
        return this.koreIdentifier;
    }

    /**
     * @param {String} koreIdentifier
     */
    setKoreIdentifier(koreIdentifier) {
        this['koreIdentifier'] = koreIdentifier;
    }

}

/**
 * @member {Array.<module:model/V1beta1Asset>} items
 */
V1beta1AssetList.prototype['items'] = undefined;

/**
 * @member {String} koreIdentifier
 */
V1beta1AssetList.prototype['koreIdentifier'] = undefined;






export default V1beta1AssetList;

