/**
 * Kore API
 * Kore API provides the frontend API (kore.appvia.io)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@appvia.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V1ServiceCatalogSpec model module.
 * @module model/V1ServiceCatalogSpec
 * @version 0.0.1
 */
class V1ServiceCatalogSpec {
    /**
     * Constructs a new <code>V1ServiceCatalogSpec</code>.
     * @alias module:model/V1ServiceCatalogSpec
     * @param serviceKindPrefix {String} 
     * @param summary {String} 
     * @param url {String} 
     */
    constructor(serviceKindPrefix, summary, url) { 
        
        V1ServiceCatalogSpec.initialize(this, serviceKindPrefix, summary, url);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, serviceKindPrefix, summary, url) { 
        obj['serviceKindPrefix'] = serviceKindPrefix;
        obj['summary'] = summary;
        obj['url'] = url;
    }

    /**
     * Constructs a <code>V1ServiceCatalogSpec</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1ServiceCatalogSpec} obj Optional instance to populate.
     * @return {module:model/V1ServiceCatalogSpec} The populated <code>V1ServiceCatalogSpec</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1ServiceCatalogSpec();

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('displayName')) {
                obj['displayName'] = ApiClient.convertToType(data['displayName'], 'String');
            }
            if (data.hasOwnProperty('serviceKindPrefix')) {
                obj['serviceKindPrefix'] = ApiClient.convertToType(data['serviceKindPrefix'], 'String');
            }
            if (data.hasOwnProperty('summary')) {
                obj['summary'] = ApiClient.convertToType(data['summary'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
        }
        return obj;
    }

/**
     * @return {String}
     */
    getDescription() {
        return this.description;
    }

    /**
     * @param {String} description
     */
    setDescription(description) {
        this['description'] = description;
    }
/**
     * @return {String}
     */
    getDisplayName() {
        return this.displayName;
    }

    /**
     * @param {String} displayName
     */
    setDisplayName(displayName) {
        this['displayName'] = displayName;
    }
/**
     * @return {String}
     */
    getServiceKindPrefix() {
        return this.serviceKindPrefix;
    }

    /**
     * @param {String} serviceKindPrefix
     */
    setServiceKindPrefix(serviceKindPrefix) {
        this['serviceKindPrefix'] = serviceKindPrefix;
    }
/**
     * @return {String}
     */
    getSummary() {
        return this.summary;
    }

    /**
     * @param {String} summary
     */
    setSummary(summary) {
        this['summary'] = summary;
    }
/**
     * @return {String}
     */
    getUrl() {
        return this.url;
    }

    /**
     * @param {String} url
     */
    setUrl(url) {
        this['url'] = url;
    }

}

/**
 * @member {String} description
 */
V1ServiceCatalogSpec.prototype['description'] = undefined;

/**
 * @member {String} displayName
 */
V1ServiceCatalogSpec.prototype['displayName'] = undefined;

/**
 * @member {String} serviceKindPrefix
 */
V1ServiceCatalogSpec.prototype['serviceKindPrefix'] = undefined;

/**
 * @member {String} summary
 */
V1ServiceCatalogSpec.prototype['summary'] = undefined;

/**
 * @member {String} url
 */
V1ServiceCatalogSpec.prototype['url'] = undefined;






export default V1ServiceCatalogSpec;

